version: "3.8"

services:
  db:
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:php8.2-apache
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "8099:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      # Opsional: set URL site supaya permalink ok
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://localhost:8099');
        define('WP_SITEURL', 'http://localhost:8099');
    volumes:
      # Naikkan limit upload/post lewat file INI custom (lihat uploads.ini di bawah)
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
      # (opsional) mount plugin folder lokal jika mau utak-atik manual
      - ./plugins:/var/www/html/wp-content/plugins
      # dipakai oleh wp-cli untuk mengambil file zip plugin
      - ./assets:/assets:ro

  wpcli:
    image: wordpress:cli-php8.2
    depends_on:
      - wordpress
    profiles: ["tools"]  # tidak auto-run kecuali dipanggil
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
    user: "33:33" # www-data di image wordpress agar permission aman
    volumes:
      - ./assets:/assets:ro
      - ./plugins:/var/www/html/wp-content/plugins
      - wp_data:/var/www/html

volumes:
  db_data:
  wp_data:

